print("O P E R A Ç Õ E S M A T E M Á T I C A S")
print("* * * * * * MENU * * * * * ")
print("Digite um operador")
print("1 - Soma \n")
print("2 - Subtração")
print("3 - Multiplicação")
print("4 - Divisão")
print("5 - par ou ímpar")
print("6 - primo")
print("7 - fatorial")
